services:
  server:
    build: ./server
    container_name: liacli-server
    expose:
      - "3001"
    env_file:
      - ./server/.env
    networks:
      - liacli-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_BASE_PATH: /liacli
    container_name: liacli-client
    expose:
      - "3000"
    env_file:
      - ./client/.env.production
    depends_on:
      - server
    networks:
      - liacli-network
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: liacli-nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    networks:
      - liacli-network
    restart: always

networks:
  liacli-network:
    driver: bridge
