services:
  server:
    build: ./server
    container_name: projeto-1-backend
    expose:
      - "3001"
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    networks:
      - cin_proxy
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_BASE_PATH: /liacli
    container_name: projeto-1-frontend
    expose:
      - "3000"
    ports:
      - "8001:3000"
    env_file:
      - ./client/.env.production
    depends_on:
      - server
    networks:
      - cin_proxy
    restart: unless-stopped

networks:
  cin_proxy:
    external: true